Avanzamenti Proof/UseCases
Secondo esempio di migration-path. Prosegue migrazione di 𝜑.

diff --git a/ita/Proof/commands/sequence b/ita/Proof/commands/sequence
--- a/ita/Proof/commands/sequence
+++ b/ita/Proof/commands/sequence
@@ -5624,6 +5624,149 @@ ip rule del fwmark 249 table ntk_from_00:16:3E:EC:A3:E1
 iptables -t mangle -D PREROUTING -m mac --mac-source 00:16:3E:EC:A3:E1 -j MARK --set-mark 249
 EOF
 
+echo "𝛿 e 𝜇 reagiscono al cambio di indirizzo di 𝜑0"
+
+cat <<EOF | lxc exec delta bash
+set -e
+ip route change unreachable 10.0.0.0/29 table ntk
+ip route change unreachable 10.0.0.64/29 table ntk
+ip route change unreachable 10.0.0.8/29 table ntk
+ip route change unreachable 10.0.0.72/29 table ntk
+ip route change unreachable 10.0.0.24/29 table ntk
+ip route change unreachable 10.0.0.88/29 table ntk
+ip route change 10.0.0.16/30 table ntk via 169.254.24.198 dev eth1 src 10.0.0.21
+ip route change 10.0.0.80/30 table ntk via 169.254.24.198 dev eth1 src 10.0.0.21
+ip route change 10.0.0.56/30 table ntk via 169.254.24.198 dev eth1 src 10.0.0.61
+ip route change unreachable 10.0.0.22/31 table ntk
+ip route change unreachable 10.0.0.86/31 table ntk
+ip route change unreachable 10.0.0.62/31 table ntk
+ip route change unreachable 10.0.0.50/31 table ntk
+ip route change 10.0.0.20/32 table ntk via 169.254.119.176 dev eth1 src 10.0.0.21
+ip route change 10.0.0.84/32 table ntk via 169.254.119.176 dev eth1 src 10.0.0.21
+ip route change 10.0.0.60/32 table ntk via 169.254.119.176 dev eth1 src 10.0.0.61
+ip route change 10.0.0.48/32 table ntk via 169.254.119.176 dev eth1 src 10.0.0.49
+ip route change 10.0.0.40/32 table ntk via 169.254.119.176 dev eth1 src 10.0.0.41
+
+ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.22/31 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.86/31 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:AF:4C:2A
+ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:AF:4C:2A
+ip route change 10.0.0.20/32 table ntk_from_00:16:3E:AF:4C:2A via 169.254.119.176 dev eth1
+ip route change 10.0.0.84/32 table ntk_from_00:16:3E:AF:4C:2A via 169.254.119.176 dev eth1
+ip route change 10.0.0.60/32 table ntk_from_00:16:3E:AF:4C:2A via 169.254.119.176 dev eth1
+ip route change 10.0.0.48/32 table ntk_from_00:16:3E:AF:4C:2A via 169.254.119.176 dev eth1
+ip route change blackhole 10.0.0.40/32 table ntk_from_00:16:3E:AF:4C:2A
+
+ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:2D:8D:DE
+ip route change 10.0.0.16/30 table ntk_from_00:16:3E:2D:8D:DE via 169.254.24.198 dev eth1
+ip route change 10.0.0.80/30 table ntk_from_00:16:3E:2D:8D:DE via 169.254.24.198 dev eth1
+ip route change 10.0.0.56/30 table ntk_from_00:16:3E:2D:8D:DE via 169.254.24.198 dev eth1
+ip route change unreachable 10.0.0.22/31 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.86/31 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.20/32 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.84/32 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.60/32 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.48/32 table ntk_from_00:16:3E:2D:8D:DE
+ip route change unreachable 10.0.0.40/32 table ntk_from_00:16:3E:2D:8D:DE
+EOF
+
+cat <<EOF | lxc exec mu bash
+set -e
+ip route change unreachable 10.0.0.0/29 table ntk
+ip route change unreachable 10.0.0.64/29 table ntk
+ip route change unreachable 10.0.0.8/29 table ntk
+ip route change unreachable 10.0.0.72/29 table ntk
+ip route change unreachable 10.0.0.24/29 table ntk
+ip route change unreachable 10.0.0.88/29 table ntk
+ip route change 10.0.0.16/30 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
+ip route change 10.0.0.80/30 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
+ip route change 10.0.0.56/30 table ntk via 169.254.253.216 dev eth1 src 10.0.0.60
+ip route change unreachable 10.0.0.22/31 table ntk
+ip route change unreachable 10.0.0.86/31 table ntk
+ip route change unreachable 10.0.0.62/31 table ntk
+ip route change unreachable 10.0.0.50/31 table ntk
+ip route change 10.0.0.21/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
+ip route change 10.0.0.85/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
+ip route change 10.0.0.61/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.60
+ip route change 10.0.0.49/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.48
+ip route change 10.0.0.41/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.40
+
+ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.22/31 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.86/31 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.21/32 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.85/32 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
+ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:1A:C4:45
+EOF
+
+echo "alfa vede beta delta e mu"
+cat <<EOF | lxc exec alfa bash
+set -e
+ping -q -n -c 1 10.0.0.19 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.19"; exit 1)
+ping -q -n -c 1 10.0.0.83 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.83"; exit 1)
+ping -q -n -c 1 10.0.0.59 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.59"; exit 1)
+ping -q -n -c 1 10.0.0.51 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.51"; exit 1)
+ping -q -n -c 1 10.0.0.41 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.41"; exit 1)
+ping -q -n -c 1 10.0.0.21 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.21"; exit 1)
+ping -q -n -c 1 10.0.0.85 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.85"; exit 1)
+ping -q -n -c 1 10.0.0.61 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.61"; exit 1)
+ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.20"; exit 1)
+ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.84"; exit 1)
+ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.60"; exit 1)
+EOF
+echo "beta vede delta e mu"
+cat <<EOF | lxc exec beta bash
+set -e
+ping -q -n -c 1 10.0.0.21 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.21"; exit 1)
+ping -q -n -c 1 10.0.0.85 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.85"; exit 1)
+ping -q -n -c 1 10.0.0.61 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.61"; exit 1)
+ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.20"; exit 1)
+ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.84"; exit 1)
+ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.60"; exit 1)
+EOF
+echo "delta vede mu"
+cat <<EOF | lxc exec delta bash
+set -e
+ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.20"; exit 1)
+ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.84"; exit 1)
+ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.60"; exit 1)
+ping -q -n -c 1 10.0.0.48 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.48"; exit 1)
+ping -q -n -c 1 10.0.0.40 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.40"; exit 1)
+EOF
+echo "gamma vede epsilon"
+cat <<EOF | lxc exec gamma bash
+set -e
+ping -q -n -c 1 10.0.0.41 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.41"; exit 1)
+EOF
+
 
 echo "test completato"
 
