Avanzamenti Proof/UseCases
Ancora test connettività 𝛼-𝛾 durante la migrazione di 𝛽.

diff --git a/ita/Proof/commands/sequence b/ita/Proof/commands/sequence
--- a/ita/Proof/commands/sequence
+++ b/ita/Proof/commands/sequence
@@ -2875,6 +2875,7 @@ lxc exec gamma -- ip route change unreachable 10.0.0.87/32 table ntk_from_00:16:
 lxc exec gamma -- ip route change unreachable 10.0.0.63/32 table ntk_from_00:16:3E:EE:AF:D1
 lxc exec gamma -- ip route change unreachable 10.0.0.51/32 table ntk_from_00:16:3E:EE:AF:D1
 lxc exec gamma -- ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:EE:AF:D1
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 echo "nuovo indirizzo temporaneamente virtuale per 𝛽2"
 lxc exec beta -- ip route add unreachable 10.0.0.0/29 table ntk
@@ -2954,6 +2955,7 @@ lxc exec beta -- iptables -t mangle -D PREROUTING -m mac --mac-source 00:16:3E:5
 
 lxc exec beta -- ip rule del fwmark 249 table ntk_from_00:16:3E:FD:E2:AA
 lxc exec beta -- iptables -t mangle -D PREROUTING -m mac --mac-source 00:16:3E:FD:E2:AA -j MARK --set-mark 249
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 echo "𝛽2 riceve gli ETP"
 lxc exec beta -- ip route change unreachable 10.0.0.0/29 table ntk
@@ -3033,6 +3035,7 @@ lxc exec beta -- ip rule add fwmark 250 table ntk_from_00:16:3E:5B:78:D5
 
 lxc exec beta -- iptables -t mangle -A PREROUTING -m mac --mac-source 00:16:3E:FD:E2:AA -j MARK --set-mark 249
 lxc exec beta -- ip rule add fwmark 249 table ntk_from_00:16:3E:FD:E2:AA
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 echo "𝛽2 (con indirizzo ancora virtuale) trasmette un ETP"
 (echo; echo "248 ntk_from_00:16:3E:EC:A3:E1 # xxx_table_ntk_from_00:16:3E:EC:A3:E1_xxx") | lxc exec gamma -- tee -a /etc/iproute2/rt_tables >/dev/null
@@ -3133,6 +3136,7 @@ lxc exec gamma -- ip route change blackhole 10.0.0.51/32 table ntk_from_00:16:3E
 lxc exec gamma -- ip route change blackhole 10.0.0.41/32 table ntk_from_00:16:3E:EC:A3:E1
 
 lxc exec gamma -- ip rule add fwmark 248 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 (echo; echo "249 ntk_from_00:16:3E:EC:A3:E1 # xxx_table_ntk_from_00:16:3E:EC:A3:E1_xxx") | lxc exec alfa -- tee -a /etc/iproute2/rt_tables >/dev/null
 lxc exec alfa -- ip route add unreachable 10.0.0.0/29 table ntk_from_00:16:3E:EC:A3:E1
@@ -3213,6 +3217,7 @@ lxc exec alfa -- ip route change unreachable 10.0.0.51/32 table ntk_from_00:16:3
 lxc exec alfa -- ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:EC:A3:E1
 
 lxc exec alfa -- ip rule add fwmark 249 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 echo "Rimozione arco *𝛽1* - *𝛼*"
 lxc exec alfa -- ip route change unreachable 10.0.0.0/29 table ntk
@@ -3259,6 +3264,7 @@ lxc exec alfa -- sed -i '/xxx_table_ntk_from_00:16:3E:EE:AF:D1_xxx/d' /etc/iprou
 lxc exec alfa -- iptables -t mangle -D PREROUTING -m mac --mac-source 00:16:3E:EE:AF:D1 -j MARK --set-mark 250
 
 lxc exec alfa -- ip route del 169.254.27.218 dev eth1 src 169.254.69.30
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 lxc exec beta -- ip netns exec migr01 ip route change unreachable 10.0.0.0/29 table ntk
 lxc exec beta -- ip netns exec migr01 ip route change unreachable 10.0.0.64/29 table ntk
@@ -3312,8 +3318,8 @@ lxc exec beta -- ip netns exec migr01 ip rule del fwmark 249 table ntk_from_00:1
 lxc exec beta -- ip netns exec migr01 ip route flush table ntk_from_00:16:3E:FD:E2:AA
 lxc exec beta -- ip netns exec migr01 iptables -t mangle -D PREROUTING -m mac --mac-source 00:16:3E:FD:E2:AA -j MARK --set-mark 249
 
-
 lxc exec beta -- ip netns exec migr01 ip route del 169.254.69.30 dev migr01_eth1 src 169.254.27.218
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
 
 
