Avanzamenti Proof/UseCases
Prosegue primo esempio di migration-path. Completa la migrazione di 𝛽.
Allinea lo script e verifica connettività.

diff --git a/ita/Proof/commands/sequence b/ita/Proof/commands/sequence
--- a/ita/Proof/commands/sequence
+++ b/ita/Proof/commands/sequence
@@ -3321,7 +3321,130 @@ lxc exec beta -- ip netns exec migr01 iptables -t mangle -D PREROUTING -m mac --
 lxc exec beta -- ip netns exec migr01 ip route del 169.254.69.30 dev migr01_eth1 src 169.254.27.218
 lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
 
+echo "Cambio indirizzo per 𝛽2"
+lxc exec beta -- ip address add 10.0.0.19 dev eth1
+lxc exec beta -- iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.19
+lxc exec beta -- ip address add 10.0.0.83 dev eth1
+lxc exec beta -- ip address add 10.0.0.59 dev eth1
+lxc exec beta -- ip address add 10.0.0.51 dev eth1
+lxc exec beta -- ip address add 10.0.0.41 dev eth1
 
+lxc exec beta -- ip route del 10.0.0.19/32 table ntk
+lxc exec beta -- ip route del 10.0.0.83/32 table ntk
+lxc exec beta -- ip route del 10.0.0.59/32 table ntk
+lxc exec beta -- ip route del 10.0.0.51/32 table ntk
+lxc exec beta -- ip route del 10.0.0.41/32 table ntk
+
+lxc exec beta -- ip route del 10.0.0.19/32 table ntk_from_00:16:3E:5B:78:D5
+lxc exec beta -- ip route del 10.0.0.83/32 table ntk_from_00:16:3E:5B:78:D5
+lxc exec beta -- ip route del 10.0.0.59/32 table ntk_from_00:16:3E:5B:78:D5
+lxc exec beta -- ip route del 10.0.0.51/32 table ntk_from_00:16:3E:5B:78:D5
+lxc exec beta -- ip route del 10.0.0.41/32 table ntk_from_00:16:3E:5B:78:D5
+
+lxc exec beta -- ip route del 10.0.0.19/32 table ntk_from_00:16:3E:FD:E2:AA
+lxc exec beta -- ip route del 10.0.0.83/32 table ntk_from_00:16:3E:FD:E2:AA
+lxc exec beta -- ip route del 10.0.0.59/32 table ntk_from_00:16:3E:FD:E2:AA
+lxc exec beta -- ip route del 10.0.0.51/32 table ntk_from_00:16:3E:FD:E2:AA
+lxc exec beta -- ip route del 10.0.0.41/32 table ntk_from_00:16:3E:FD:E2:AA
+
+lxc exec beta -- ip route change unreachable 10.0.0.0/29 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.64/29 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.8/29 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.72/29 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.24/29 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.88/29 table ntk
+lxc exec beta -- ip route change 10.0.0.20/30 table ntk via 169.254.94.223 dev eth1 src 10.0.0.19
+lxc exec beta -- ip route change 10.0.0.84/30 table ntk via 169.254.94.223 dev eth1 src 10.0.0.19
+lxc exec beta -- ip route change 10.0.0.60/30 table ntk via 169.254.94.223 dev eth1 src 10.0.0.59
+lxc exec beta -- ip route change unreachable 10.0.0.16/31 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.80/31 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.56/31 table ntk
+lxc exec beta -- ip route change unreachable 10.0.0.48/31 table ntk
+lxc exec beta -- ip route change 10.0.0.18/32 table ntk via 169.254.69.30 dev eth1 src 10.0.0.19
+lxc exec beta -- ip route change 10.0.0.82/32 table ntk via 169.254.69.30 dev eth1 src 10.0.0.19
+lxc exec beta -- ip route change 10.0.0.58/32 table ntk via 169.254.69.30 dev eth1 src 10.0.0.59
+lxc exec beta -- ip route change 10.0.0.50/32 table ntk via 169.254.69.30 dev eth1 src 10.0.0.51
+lxc exec beta -- ip route change 10.0.0.40/32 table ntk via 169.254.69.30 dev eth1 src 10.0.0.41
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
+
+lxc exec alfa -- ip route change unreachable 10.0.0.0/29 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.64/29 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.8/29 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.72/29 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.24/29 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.88/29 table ntk
+lxc exec alfa -- ip route change 10.0.0.20/30 table ntk via 169.254.96.141 dev eth1 src 10.0.0.18
+lxc exec alfa -- ip route change 10.0.0.84/30 table ntk via 169.254.96.141 dev eth1 src 10.0.0.18
+lxc exec alfa -- ip route change 10.0.0.60/30 table ntk via 169.254.96.141 dev eth1 src 10.0.0.58
+lxc exec alfa -- ip route change unreachable 10.0.0.16/31 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.80/31 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.56/31 table ntk
+lxc exec alfa -- ip route change unreachable 10.0.0.48/31 table ntk
+lxc exec alfa -- ip route change 10.0.0.19/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.18
+lxc exec alfa -- ip route change 10.0.0.83/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.18
+lxc exec alfa -- ip route change 10.0.0.59/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.58
+lxc exec alfa -- ip route change 10.0.0.51/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.50
+lxc exec alfa -- ip route change 10.0.0.41/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.40
+
+lxc exec alfa -- ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.20/30 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.84/30 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.60/30 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.16/31 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.80/31 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.56/31 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.48/31 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.19/32 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.83/32 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.59/32 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.51/32 table ntk_from_00:16:3E:EC:A3:E1
+lxc exec alfa -- ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:EC:A3:E1
+
+echo "alfa vede beta gamma delta e mu"
+lxc exec alfa -- ping -q -n -c 1 10.0.0.19 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.19"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.83 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.83"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.59 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.59"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.51 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.51"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.41 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.41"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.22 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.22"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.86 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.86"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.62"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.21 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.21"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.85 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.85"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.61 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.61"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.20"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.84"; exit 1)
+lxc exec alfa -- ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "alfa: errore ping 10.0.0.60"; exit 1)
+echo "beta vede gamma delta e mu"
+lxc exec beta -- ping -q -n -c 1 10.0.0.22 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.22"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.86 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.86"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.62"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.21 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.21"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.85 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.85"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.61 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.61"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.20"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.84"; exit 1)
+lxc exec beta -- ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "beta: errore ping 10.0.0.60"; exit 1)
+echo "gamma vede delta e mu"
+lxc exec gamma -- ping -q -n -c 1 10.0.0.21 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.21"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.85 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.85"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.61 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.61"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.49 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.49"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.20"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.84"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.60"; exit 1)
+lxc exec gamma -- ping -q -n -c 1 10.0.0.48 -W 1 &>/dev/null || (echo "gamma: errore ping 10.0.0.48"; exit 1)
+echo "delta vede mu"
+lxc exec delta -- ping -q -n -c 1 10.0.0.20 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.20"; exit 1)
+lxc exec delta -- ping -q -n -c 1 10.0.0.84 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.84"; exit 1)
+lxc exec delta -- ping -q -n -c 1 10.0.0.60 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.60"; exit 1)
+lxc exec delta -- ping -q -n -c 1 10.0.0.48 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.48"; exit 1)
+lxc exec delta -- ping -q -n -c 1 10.0.0.40 -W 1 &>/dev/null || (echo "delta: errore ping 10.0.0.40"; exit 1)
 
 echo "test completato"
 
