Avanzamenti Proof/UseCases
Considerazioni sui test.

diff --git a/ita/Proof/commands/sequence b/ita/Proof/commands/sequence
--- a/ita/Proof/commands/sequence
+++ b/ita/Proof/commands/sequence
@@ -509,7 +509,11 @@ ssh beta sudo ip netns del entr02
 ssh gamma sudo ip route del 169.254.215.29 dev eth1 src 169.254.94.223
 
 echo "beta vede gamma e viceversa"
-ssh beta "ping -q -n -c 1 10.0.0.40 -W 1 &>/dev/null" || (echo "beta non vede gamma"; exit 1)
+ssh beta "ping -q -n -c 1 10.0.0.22 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.22"; exit 1)
+ssh beta "ping -q -n -c 1 10.0.0.86 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.86"; exit 1)
+ssh beta "ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.62"; exit 1)
+ssh beta "ping -q -n -c 1 10.0.0.50 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.50"; exit 1)
+ssh beta "ping -q -n -c 1 10.0.0.40 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.40"; exit 1)
 
 echo "test completato"
 
